### ISSUE TITLE
Service statuses not appear

### ISSUE THREAD

**Issue by ZweiTiger** [dugalex/DA-Enhanced-Pro#1]
Hi :)

I like your theme. But the service statuses not appear for me. Here is a picture:
http://kepfeltoltes.hu/151221/notwork_www.kepfeltoltes.hu_.png

SSL ON

**Comment by dugalex** [comment]
What are your server specs. I remember them not displaying sometimes on a smaller vps.
I believe it had something to do with php (version or type).
Since I've been using php-fpm I never had that problem.

**Comment by ZweiTiger** [comment]
Hi :)

Online.net Dedicated Server - Cloudlinux operation system.(cageFS and php selector) And PHP 5.4 by default

**Comment by dugalex** [comment]
Are you running apache or nginx? The script checks for "httpd" and if it's not running it doesn't display anything. I remember having that with nginx, then when I changed to nginx_apache it worked.
If that's the case, can you please try and edit the file: inc/functions/status.html

from:

``` html
    function getServices() {
        $str = $this->api_get('/CMD_API_SHOW_SERVICES');
        if(strpos($str, 'httpd') == false) return false;
        parse_str(urldecode($str), $servArr);
        return $servArr;
    }
```

to:

``` html
    function getServices() {
        $str = $this->api_get('/CMD_API_SHOW_SERVICES');
        if(strpos($str, 'directadmin') == false) return false;
        parse_str(urldecode($str), $servArr);
        return $servArr;
    }
```

Basically change httpd to directadmin and let me know if it works.
Since it works on my end eider way I don't know if this will do the trick.

Regards,
Alex

**Comment by ZweiTiger** [comment]
Hi :)

I run litespeed webserver. Now its appear but.. seems not too correct. The litespeed is running very well. But its says its offline.

http://kepfeltoltes.hu/151221/almost_www.kepfeltoltes.hu_.png

Check the picture :)

**Comment by dugalex** [comment]
It's a code from the old Capri skin. I'm no programmer and don't really know php, but I'll see if I can figure something out.

**Comment by dugalex** [comment]
The dovecot being out of order can be caused if you've increased the font size.
You would need to increase the margin in "inc/css/style-blue.css" at:

``` html
.service_on, .service_off {
    margin:4px;
...
}
```

**Comment by dugalex** [comment]
The services get status from https://yourdomain.com:2222/CMD_API_SHOW_SERVICES
Whatever is shown on that link is what this show.
Actually, I think that your "lfd" is off as the services circle has been moved down by one line :) because of Dovecot being out of line.

**Comment by dugalex** [comment]
It should be fixed now. I've added an extra div to keep it in line.

**Comment by ZweiTiger** [comment]
Hmm.. Thank you! Now its working :) . Great work!
