### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by ZweiTiger** [dugalex/DA-Enhanced-Pro#2]
Hey,

Just a bug report for you :)

1, The real ram usage not show the 'real' memory usage. Example: with htop the real ram usage is 2,7GB but at directadmin its say 5,7GB.

2, Some menus are strange. Here is a picture:
http://kepfeltoltes.hu/151221/strange_www.kepfeltoltes.hu_.png

Thats all for now

**Comment by dugalex** [comment]
1. What system are you using? I've only tested this on centos 6 as that's the only system with DA I have access to. Can you send me a pic of this too.
2. Fixed. In "pro_header_bar.html" I had:

``` html
<td valign=top">
```

instead of  

``` html
<td valign=top>
```

**Comment by ZweiTiger** [comment]
1, Centos 6 - Cloudlinux 6
2,

Wrong: http://kepfeltoltes.hu/151222/wrong1_www.kepfeltoltes.hu_.png
Correct: http://kepfeltoltes.hu/151222/wrong2_www.kepfeltoltes.hu_.png

Real ram usage is incorrect. And i suggest you to change RAM usage > Real RAM. Its easier for admins i think to realize.

**Comment by dugalex** [comment]
Do you get proper values when you run:

``` html
cat /proc/meminfo
```

**Comment by dugalex** [comment]
I've swapped Real RAM with RAM Usage as suggested :)

**Comment by ZweiTiger** [comment]
Nice. Now i think great! Thank you very much for your help and for this useful theme :)
